version: '3'
networks:
  project:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: app
    ports:
      - "8000:8000"
    restart: always
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DBNAME: ${MYSQL_DBNAME}
      MYSQL_PORT: ${MYSQL_PORT}
      EMAIL_BACKEND: ${EMAIL_BACKEND}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - mysql
    networks:
      - project  # Conectando a la red default

  mysql:
    container_name: projectMysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DBNAME}
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ~/mysql-data:/var/lib/mysql
    networks:
      - project 