version: '3'

services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: app
    ports:
      - "8000:8000"
    restart: always
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DBNAME: ${MYSQL_DBNAME}
      MYSQL_PORT: ${MYSQL_PORT}
      EMAIL_BACKEND: ${EMAIL_BACKEND}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - mysql
    networks:
      default:  # Conectando a la red default
  mysql:
    container_name: some-mysql
    image: mysql:latest
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - default 