# Use an official Python runtime as a parent image
FROM python:3.9

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /code

# Install dependencies
COPY requeriments.txt /code/
RUN pip install --no-cache-dir -r requeriments.txt

# Copy the project code into the container
COPY . /code/

# Expose the port the app runs on
EXPOSE 8000

# Define the command to run your application
CMD ["python", "manage.py", "runserver", "127.0.0.0:8000"]
