# Generated by Django 4.2.7 on 2023-11-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedidoproducto_producto_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='total_pedido',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
