# Generated by Django 4.2.7 on 2023-11-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carritos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoproducto',
            name='imagen',
            field=models.CharField(default='', max_length=500),
        ),
    ]
